[package]
name = 'DexlynClmm'
version = '0.0.2'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
dexlyn_clmm = "0x34287fd1fae969ae6dca12afb9cd6e95da58aa7a1ddbd19a20138729b2996870"


[dependencies.AptosToken]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/aptos-token'
rev = 'dev'


[dependencies.IntegerMate]
local = "../IntegerMate"