[package]
name = 'IntegerMate'
version = '1.0.0'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
integer_mate = "0x48516d04d942d36299e6fb018865f0ac4b1ca37e2a1518ca367c7960c4b30985"

[dependencies.AptosTokenObjects]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/aptos-token-objects"